# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [2]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [3]:
from google.colab import files
import json

uploaded = files.upload()

# Assuming the uploaded file is 'winemag-data-130k-v2.json'
file_name = "winemag-data-130k-v2.json"  # Adjust as needed based on the uploaded file's name

# Load the dataset
with open(file_name, "rb") as json_data:
    wine_data = json.load(json_data)

# Example: Print the first entry to verify it's loaded correctly
print(wine_data[0])


Saving winemag-data-130k-v2.json to winemag-data-130k-v2.json
{'points': '87', 'title': 'Nicosia 2013 Vulkà Bianco  (Etna)', 'description': "Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.", 'taster_name': 'Kerin O’Keefe', 'taster_twitter_handle': '@kerinokeefe', 'price': None, 'designation': 'Vulkà Bianco', 'variety': 'White Blend', 'region_1': 'Etna', 'region_2': None, 'province': 'Sicily & Sardinia', 'country': 'Italy', 'winery': 'Nicosia'}


In [4]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [5]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [6]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [7]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [8]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [9]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [10]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [11]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [12]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [13]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [14]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [15]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [16]:
example_input_output = train_ds.take(1).get_single_element()

In [17]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,  152,    2, 1565,    2,  230,   24,    2,   57,
          5,   38,    3,   11,   68,   34,    5,   37,   67,   16,    4,
         15,   13,  246,    3,   80,  148, 1513,    8,  249,    9,  232,
         34,    4,    6,   22, 1070,    3,  429,    8,  597,    3,  822,
          7,    4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [18]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,  152,    2, 1565,    2,  230,   24,    2,   57,    5,
         38,    3,   11,   68,   34,    5,   37,   67,   16,    4,   15,
         13,  246,    3,   80,  148, 1513,    8,  249,    9,  232,   34,
          4,    6,   22, 1070,    3,  429,    8,  597,    3,  822,    7,
          4,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [19]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [20]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [21]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [22]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [23]:
gpt.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 token_and_position_embeddi  (None, None, 256)         2580480   
 ng (TokenAndPositionEmbedd                                      
 ing)                                                            
                                                                 
 transformer_block (Transfo  ((None, None, 256),       658688    
 rmerBlock)                   (None, 2, None, None))             
                                                                 
 dense_2 (Dense)             (None, None, 10000)       2570000   
                                                                 
Total params: 5809168 (22.16 MB)
Trainable params: 5809168 (22.16 MB)
Non-trainable params: 0 (0.00 Byte)
_____________________

In [24]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [25]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [26]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.ckpt",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [27]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4060/4060 [==============================] - ETA: 0s - loss: 2.2483 - dense_2_loss: 2.2483
generated text:
wine review : australia : south australia : pinot grigio : a good buy . if give this fun fruit - driven wine is clean , crisp and vibrant . with its bold quality does need a keen edge to allow it to age and integrate . 

4060/4060 [==============================] - 166s 39ms/step - loss: 2.2483 - dense_2_loss: 2.2483
Epoch 2/5
4060/4060 [==============================] - ETA: 0s - loss: 1.9582 - dense_2_loss: 1.9582
generated text:
wine review : us : california : petit verdot : there ' s an edge of toasted oak to this full - bodied , dense nose is almost syrupy . the aromas resemble prunes , raisin cola and toffee and brown sugar jam . great fruit flavors come across the palate and quite concentrated in dusty and second . 

4060/4060 [==============================] - 124s 30ms/step - loss: 1.9582 - dense_2_loss: 1.9582
Epoch 3/5
4059/4060 [============================>.

In [28]:
# Save the final model
gpt.save("./models/gpt")

# 3. Generate text using the Transformer

In [29]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [35]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=0.6
)


generated text:
wine review : us : california : chardonnay : this is a pretty chardonnay , but it ' s very dry and crisp in acidity . it ' s a little thin in the way , with rich flavors of pineapples , pears and buttered toast . 



In [33]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.2
)


generated text:
wine review : italy : tuscany : sangiovese : this wine opens with aromas of leafy underbrush , scorched earth , leather , game and a whiff of game . the palate offers dried black cherry , licorice , clove and a hint of game alongside fine - grained tannins . 



In [32]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : rich and sweet , this is a bit concentrated in flavor and a hint of honey and apricot flavors . it ' s a bit rustic but not overbearing , with its juicy acidity and delicate body . 



::   	100.0%
-:   	0.0%
grosso:   	0.0%
zealand:   	0.0%
africa:   	0.0%
--------



mosel:   	95.17%
rheinhessen:   	2.84%
rheingau:   	1.14%
nahe:   	0.48%
franken:   	0.26%
--------



::   	99.57%
-:   	0.43%
spice:   	0.0%
grosso:   	0.0%
other:   	0.0%
--------



riesling:   	100.0%
pinot:   	0.0%
dornfelder:   	0.0%
cabernet:   	0.0%
sparkling:   	0.0%
--------



::   	100.0%
-:   	0.0%
blend:   	0.0%
grosso:   	0.0%
sekt:   	0.0%
--------



a:   	23.02%
this:   	18.15%
while:   	13.92%
whiffs:   	6.46%
fresh:   	4.59%
--------



and:   	63.04%
,:   	29.04%
yellow:   	4.02%
honey:   	1.2%
notes:   	0.61%
--------



ripe:   	24.24%
fruity:   	13.21%
luscious:   	8.43%
savory:   	7.79%
juicy:   	7.47%
--------



,:   	71.22%
on:   	18.64%
in:   	7.92%
with:   	1.32%
-:   	0.4%
--------



this:   	51.48%
with:   	43.05%
but:   	3.82%
yet:   	0.92%
it:   	0.43%
--------



is:   	40.72%
luscious:   	6.38%
delicately:   	4.1%
ripe:   	3.6%
lush:   	3.47%
--------



a:   	98.46%
an:   	1.43%
the:   	0.02%
one:   	0.01%
lusciously:   	0.01%
--------



bit:   	24.09%
luscious:   	9.87%
ripe:   	8.75%
delicate:   	6.65%
delicious:   	4.12%
--------



rustic:   	22.35%
simple:   	13.35%
soft:   	10.32%
heavy:   	7.97%
more:   	5.22%
--------



,:   	40.58%
in:   	25.99%
and:   	14.01%
on:   	10.74%
with:   	5.74%
--------



flavor:   	38.69%
style:   	24.12%
the:   	19.15%
its:   	4.16%
fruit:   	2.72%
--------



,:   	57.19%
and:   	27.21%
.:   	10.82%
intensity:   	1.8%
yet:   	1.22%
--------



texture:   	20.05%
a:   	15.65%
forward:   	12.26%
intensity:   	9.57%
body:   	7.84%
--------



hint:   	23.81%
bit:   	22.96%
touch:   	8.99%
long:   	6.27%
plush:   	3.83%
--------



of:   	100.0%
at:   	0.0%
that:   	0.0%
to:   	0.0%
-:   	0.0%
--------



honey:   	60.8%
smoke:   	5.09%
sweet:   	4.86%
petrol:   	3.84%
sweetness:   	2.84%
--------



on:   	32.96%
and:   	32.24%
.:   	14.03%
,:   	11.54%
-:   	5.9%
--------



marmalade:   	29.51%
spice:   	16.87%
lemon:   	9.35%
peach:   	7.3%
tangerine:   	6.79%
--------



notes:   	31.28%
nectar:   	27.19%
flavors:   	25.15%
.:   	4.83%
preserves:   	3.76%
--------



.:   	78.43%
,:   	19.35%
on:   	1.21%
that:   	0.53%
and:   	0.26%
--------



it:   	95.08%
the:   	3.8%
a:   	0.3%
there:   	0.17%
:   	0.1%
--------



':   	99.95%
finishes:   	0.04%
penetrates:   	0.0%
is:   	0.0%
has:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
d:   	0.0%
re:   	0.0%
07:   	0.0%
--------



a:   	96.3%
an:   	1.91%
lusciously:   	0.21%
delicate:   	0.09%
not:   	0.09%
--------



bit:   	85.18%
touch:   	2.16%
delicate:   	2.14%
fine:   	1.51%
plush:   	0.77%
--------



more:   	17.07%
lean:   	11.86%
rustic:   	8.92%
soft:   	8.17%
sweet:   	6.96%
--------



,:   	62.46%
and:   	27.68%
in:   	4.48%
but:   	2.6%
with:   	1.02%
--------



it:   	44.88%
the:   	15.75%
a:   	12.35%
not:   	10.43%
finishes:   	1.86%
--------



particularly:   	41.33%
unpleasant:   	28.61%
overly:   	8.11%
overbearing:   	7.63%
terribly:   	2.6%
--------



,:   	95.39%
.:   	4.11%
or:   	0.32%
in:   	0.1%
;:   	0.03%
--------



with:   	49.46%
but:   	42.05%
and:   	5.33%
finishing:   	0.99%
though:   	0.36%
--------



a:   	97.43%
an:   	1.15%
its:   	0.4%
the:   	0.21%
just:   	0.14%
--------



long:   	17.02%
lingering:   	16.47%
delicate:   	14.53%
[UNK]:   	6.9%
alcohol:   	4.23%
--------



acidity:   	50.82%
demeanor:   	37.04%
,:   	3.25%
acids:   	2.41%
fruit:   	0.86%
--------



and:   	90.7%
,:   	4.46%
.:   	3.37%
is:   	0.91%
cutting:   	0.2%
--------



a:   	66.62%
delicate:   	13.29%
balance:   	1.77%
primary:   	1.46%
tannins:   	1.32%
--------



pétillance:   	41.15%
demeanor:   	21.36%
sweetness:   	6.76%
balance:   	4.59%
texture:   	4.18%
--------



.:   	93.88%
,:   	5.03%
and:   	0.7%
to:   	0.08%
through:   	0.05%
--------



:   	92.06%
drink:   	4.18%
it:   	2.85%
the:   	0.56%
a:   	0.15%
--------

